; general mail config
[mail]
mail_to = "your-backend@example.com";
mail_subject = "[Just Contact Backend] new message";

; SMTP settings
[SMTP]
smtp_agent = "mail" ; "mail" to use systems mail server such as sendmail or Postfix, 
; set smtp_agent to "SMTP" to use external host
smtp_from = "no-reply@example.com" ; PHPMailer uses root@localhost as default from
; when agent is SMTP you need to provide the following information
smtp_host = ""; server to use, e.g., smtp.google.com
smtp_port = "587" ; the smtp port to use
smtp_username = "" ; user to login to smtp_host
smtp_password = "" ; password to login to smtp_host

